### ISSUE TITLE
homebrew

### ISSUE THREAD

**Issue by ec1oud** [F1ash/qt-virt-manager#53]
It's mentioned that there is experimental homebrew support on macOS.  I think the README should explain how to get that working. I searched the repo and found in .travis.yml `brew tap F1ash/homebrew-qt-virt-manager`. 
```
[strm][15:13:31] brew tap F1ash/homebrew-qt-virt-manager
==> Tapping f1ash/qt-virt-manager
Cloning into '/usr/local/Homebrew/Library/Taps/f1ash/homebrew-qt-virt-manager'...
remote: Enumerating objects: 270, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 270 (delta 0), reused 0 (delta 0), pack-reused 269
Receiving objects: 100% (270/270), 33.50 KiB | 1.15 MiB/s, done.
Resolving deltas: 100% (160/160), done.
Tapped 7 formulae (19 files, 55.3KB).

[strm][15:17:14] brew search qt-virt
==> Formulae
f1ash/qt-virt-manager/libvirt-glib ✔                  f1ash/qt-virt-manager/qtermwidget                     f1ash/qt-virt-manager/usbredir ✔
f1ash/qt-virt-manager/libvnc                          f1ash/qt-virt-manager/spice-client-glib2
f1ash/qt-virt-manager/qt-virt-manager                 f1ash/qt-virt-manager/spice-protocol ✔

[strm][15:17:28] brew install qt-virt-manager
Error: qt-virt-manager: Unsupported special dependency :x11
```
Yeah I hope it doesn't really depend on X11, but I have XQuartz FWIW.

**Comment by ec1oud** [comment]
maybe just get dependencies and then build from source?
```
$ brew install libvnc qtermwidget spice-client-glib2 qtermwidget
Error: invalid attribute for formula 'f1ash/qt-virt-manager/qtermwidget': version (nil)
/usr/local/Homebrew/Library/Homebrew/formula.rb:294:in `validate_attributes!'
/usr/local/Homebrew/Library/Homebrew/formula.rb:219:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:307:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:307:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:560:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:626:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:622:in `map'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:622:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:307:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:145:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```
